export const data = [
  {
    upc: '4011',
    description: 'bananas',
    dept: 5,
    deptDescription: 'Produce',
    category: 11,
    categoryDescription: 'produce',
    price: 0.69,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '',
    tprEndDate: '',
    vendorId: 'PROD',
    vendorCode: 425794,
    uom: 'C',
    baseCost: 0.5,
    case: 1,
  },
  {
    upc: '00000000000117',
    description: 'SnapCrack Treats ',
    dept: 32,
    deptDescription: 'Soda/Candy',
    category: 4,
    categoryDescription: 'CANDY & GUM',
    price: 1.1,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.05,
    tprStartDate: '5/8/2022',
    tprEndDate: '5/14/2022',
    vendorId: 'ABC',
    vendorCode: 325794,
    uom: 'C',
    baseCost: 0.99,
    case: 1,
  },
  {
    upc: '00000000000118',
    description: 'Twizzlers',
    dept: 32,
    deptDescription: 'Soda/Candy',
    category: 4,
    categoryDescription: 'CANDY & GUM',
    price: 2.65,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.89,
    tprStartDate: '9/1/2022',
    tprEndDate: '9/30/2022',
    vendorId: 'ABC',
    vendorCode: 325694,
    uom: 'C',
    baseCost: 1.99,
    case: 1,
  },
  {
    upc: '00000000000119',
    description: 'Rolos',
    dept: 32,
    deptDescription: 'Soda/Candy',
    category: 4,
    categoryDescription: 'CANDY & GUM',
    price: 1.79,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.69,
    tprStartDate: '9/1/2022',
    tprEndDate: '9/30/2022',
    vendorId: 'ABC',
    vendorCode: 325793,
    uom: 'C',
    baseCost: 1.69,
    case: 1,
  },
  {
    upc: '00000000000120',
    description: 'Gummie Bears',
    dept: 32,
    deptDescription: 'Soda/Candy',
    category: 4,
    categoryDescription: 'CANDY & GUM',
    price: 2.1,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.69,
    tprStartDate: '',
    tprEndDate: '',
    vendorId: 'ABC',
    vendorCode: 325694,
    uom: 'C',
    baseCost: 2.05,
    case: 1,
  },
  {
    upc: '0006414428243',
    description: 'ROTEL DC TOM/GR CHL ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 3,
    categoryDescription: 'BAKING NEEDS',
    price: 1.49,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.29,
    tprStartDate: '4/13/2022',
    tprEndDate: '9/1/2022',
    vendorId: '',
    vendorCode: null,
    uom: '',
    baseCost: 0,
    case: 1,
  },
  {
    upc: '0006414428263',
    description: 'ROTEL MLD TOM GR CHL 10 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 3,
    categoryDescription: 'BAKING NEEDS',
    price: 1.49,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.29,
    tprStartDate: '4/13/2022',
    tprEndDate: '9/1/2022',
    vendorId: '',
    vendorCode: null,
    uom: '',
    baseCost: 0,
    case: 1,
  },
  {
    upc: '0006414428266',
    description: 'ROTEL X HOT DC TOM 10 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 3,
    categoryDescription: 'BAKING NEEDS',
    price: 1.49,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 1.29,
    tprStartDate: '4/13/2022',
    tprEndDate: '9/1/2022',
    vendorId: '',
    vendorCode: null,
    uom: '',
    baseCost: 0,
    case: 1,
  },
  {
    upc: '0001760008102',
    description: 'CASA TACO SHELLS 4.5 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 9,
    categoryDescription: 'COOKIES - CRACKERS - MISCELLAN',
    price: 2.19,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 112345,
    uom: 'U',
    baseCost: 1.99,
    case: 1,
  },
  {
    upc: '0001760008120',
    description: 'CASA TACO DINNER 9.75 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 9,
    categoryDescription: 'COOKIES - CRACKERS - MISCELLAN',
    price: 2.79,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 112344,
    uom: 'U',
    baseCost: 2.59,
    case: 1,
  },
  {
    upc: '0001760008122',
    description: 'CASA TACO SEASONING 1.25 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 9,
    categoryDescription: 'COOKIES - CRACKERS - MISCELLAN',
    price: 0.79,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 112343,
    uom: 'U',
    baseCost: 0.59,
    case: 1,
  },
  {
    upc: '0001760008557',
    description: 'CASA TACO SALAD SEAS 1.25 OZ',
    dept: 1,
    deptDescription: 'Grocery',
    category: 9,
    categoryDescription: 'COOKIES - CRACKERS - MISCELLAN',
    price: 1.69,
    qty: 1,
    isWeightRequired: false,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 112342,
    uom: 'U',
    baseCost: 1.29,
    case: 1,
  },
  {
    upc: '0020000400000',
    description: 'Carnitas',
    dept: 9,
    deptDescription: 'Meat',
    category: 6198,
    categoryDescription: 'MISC SIDE MEATS',
    price: 1.99,
    qty: 1,
    isWeightRequired: true,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 221456,
    uom: 'U',
    baseCost: 0.99,
    case: 1,
  },
  {
    upc: '0020000600000',
    description: 'Barbacoa',
    dept: 9,
    deptDescription: 'Meat',
    category: 6198,
    categoryDescription: 'MISC SIDE MEATS',
    price: 3.59,
    qty: 1,
    isWeightRequired: true,
    pack: 'each',
    tprPrice: 0,
    tprStartDate: '0',
    tprEndDate: '0',
    vendorId: '00050',
    vendorCode: 190263,
    uom: 'U',
    baseCost: 2.59,
    case: 1,
  },
];
